{
 "title": "Adguard Exporter",
 "description": "This is a Adguard dashboard when using the https://github.com/ebrianne/adguard-exporter Prometheus exporter",
 "tags": [ "adguard" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(adguard_num_dns_queries, hostname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "AdGuard Home", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adguard_running{hostname=~'$node'}"
    }
   ]
  },
  {
   "title": "Protection",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adguard_protection_enabled{hostname=~'$node'}"
    }
   ]
  },
  {
   "title": "Processing TIme",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "adguard_avg_processing_time{hostname=~'$node'}",
     "legendFormat": "{{ legend }}"
    }
   ]
  },
  {
   "title": "Number of queries",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adguard_num_dns_queries{hostname=~'$node'}"
    }
   ]
  },
  {
   "title": "Domains being blocked",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adguard_num_blocked_filtering{hostname=~'$node'}"
    }
   ]
  },
  {
   "title": "Percent of ads blocked",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adguard_num_blocked_filtering{hostname=~'$node'} / adguard_num_dns_queries{hostname=~'$node'} * 100"
    }
   ]
  },
  {
   "title": "Top queries by domain",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,adguard_top_queried_domains{hostname=~'$node'})",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "Top ads by domain",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, adguard_top_blocked_domains{hostname=~'$node'})",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "DNS queries all of types",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "adguard_num_dns_queries{hostname=~'$node'}",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "DNS Query Types",
   "type": "graph",
   "gridPos": { "h": 11, "w": 7, "x": 11, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "adguard_query_types{hostname=~'$node'}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Replies by type",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adguard_query_types{hostname=~'$node'}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Top clients by source",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(7, adguard_top_clients{hostname=~'$node'})",
     "legendFormat": "{{ client }}"
    }
   ]
  },
  {
   "title": "Ads blocked",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "adguard_num_blocked_filtering{hostname=~'$node'}",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Top clients",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 15 },
   "targets": [
    {
     "expr": "adguard_top_clients{hostname=~'$node'}",
     "legendFormat": "{{ client }}"
    }
   ]
  },
  {
   "title": "% of ads blocked",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "adguard_num_blocked_filtering{hostname=~'$node'} / adguard_num_dns_queries{hostname=~'$node'} * 100",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Top ads domains",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 24 },
   "targets": [
    {
     "expr": "adguard_top_blocked_domains{hostname=~'$node'}",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "Top queries",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "adguard_top_queried_domains{hostname=~'$node'}",
     "legendFormat": "{{ domain }}"
    }
   ]
  }
 ]
}