apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: urlshortener

helmCharts:
  - name: urlshortener
    repo: https://spechtlabs.github.io/helm-charts
    version: 0.0.15
    releaseName: urlshortener
    namespace: urlshortener
    valuesFile: helm-values.yaml
