apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: adguard
  namespace: monitoring
spec:
  groups:
    - name: adguard
      rules:
        - alert: AdGuardProtectionDisabled
          annotations:
            message: AdGuard Server {{ $labels.hostname }} has protection disabled for 24h
          expr: |
            sum by (hostname) (adguard_protection_enabled) == 0
          for: 24h
          labels:
            severity: critical
        - alert: AdGuardNotRunning
          annotations:
            message: AdGuard Server {{ $labels.hostname }} not running for 24h
          expr: |
            sum by (hostname) (adguard_running) == 0
          for: 24h
          labels:
            severity: critical
        - alert: AdGuardDnsRequestsAbnormal
          annotations:
            message: |
              AdGuard Server {{ $labels.hostname }} is seeing an abnormal number of DNS Querys!
              Currently seeing {{ printf "%f" $value }} standard deviations in DNS requests relative to the last 90 days.
          expr: |
            (
              (
                # subtract the average of the last 7d from the last 1d to better understand
                # how the current average compares to historical averages
                (
                  avg_over_time(adguard_num_dns_queries[1d]) # calculates the average dns_query count over 1 hour
                  - avg_over_time(adguard_num_dns_queries[7d]) # calculates the average dns_query count over 48h hours
                )

                # divide the result from by the standard deviation of the dns_query count over the last 90 days
                # The standard deviation measures the spread or dispersion of a set of data points.
                # In this context, it helps in understanding how much the current value deviates from the historical average.
                / stddev_over_time(adguard_num_dns_queries[90d])

                # if this standard deviation is larger than 2, we want to know because something is causing
                # much more DNS queries than usual
                > 2
              )
              or
              (
                # subtract the average of the last 7d from the last 1d to better understand
                # how the current average compares to historical averages
                (
                  avg_over_time(adguard_num_dns_queries[1d]) # calculates the average dns_query count over 1 hour
                  - avg_over_time(adguard_num_dns_queries[7d]) # calculates the average dns_query count over 48h hours
                )

                # divide the result from by the standard deviation of the dns_query count over the last 90 days
                # The standard deviation measures the spread or dispersion of a set of data points.
                # In this context, it helps in understanding how much the current value deviates from the historical average.
                / stddev_over_time(adguard_num_dns_queries[90d])

                # if this standard deviation is smaller than -2, we want to know because something is causing
                # muss less DNS queries than usual
                < -2
              )
            )
          for: 1d
          labels:
            severity: warning
        - alert: AdGuardDnsAdBlocksAbnormal
          annotations:
            message: |
              AdGuard Server {{ $labels.hostname }} is seeing an abnormal number of blocked DNS Querys!
              Currently seeing {{ printf "%f" $value }} standard deviations in blocked DNS requests relative to the last 7 days.
          expr: |
            (
              (
                # subtract the average of the last 7d from the last 1d to better understand
                # how the current average compares to historical averages
                (
                  avg_over_time(adguard_num_blocked_filtering[1d]) # calculates the average blocked dns_query count over 1 day
                  - avg_over_time(adguard_num_blocked_filtering[7d]) # calculates the average blocked dns_query count over 7 days
                )

                # divide the result from by the standard deviation of the blocked dns_query count over the last 30 days
                # The standard deviation measures the spread or dispersion of a set of data points.
                # In this context, it helps in understanding how much the current value deviates from the historical average.
                / stddev_over_time(adguard_num_blocked_filtering[30d])

                # if this standard deviation is larger than 2, we want to know because something is causing way more
                # blocked DNS queries than usual
                > 2
              )
              or
              (
                # subtract the average of the last 7d from the last 1d to better understand
                # how the current average compares to historical averages
                (
                  avg_over_time(adguard_num_blocked_filtering[1d]) # calculates the average blocked dns_query count over 1 day
                  - avg_over_time(adguard_num_blocked_filtering[7d]) # calculates the average blocked dns_query count over 7 days
                )

                # divide the result from by the standard deviation of the blocked dns_query count over the last 30 days
                # The standard deviation measures the spread or dispersion of a set of data points.
                # In this context, it helps in understanding how much the current value deviates from the historical average.
                / stddev_over_time(adguard_num_blocked_filtering[30d])

                # if this standard deviation is smaller than -2, we want to know because something is causing way less
                # blocked DNS queries than usual
                < -1
              )
            )
          for: 1d
          labels:
            severity: warning
