{
 "title": "Hetzner Cloud Servers",
 "description": "Dashboard for listing information about servers in the Hetzner Cloud using metrics from https://promhippie.github.io/hcloud_exporter/",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "servers",
    "query": {
     "query": "label_values(hcloud_server_running, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Servers Running",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "hcloud_server_running", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Monthly cost",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(vat) (hcloud_server_price_monthly{vat=\"gross\"}) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Servers running",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(hcloud_server_running)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Incoming Traffic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (datacenter) (hcloud_server_incoming_traffic_bytes)",
     "legendFormat": "{{datacenter}}"
    },
    {
     "expr": "sum (hcloud_server_incoming_traffic_bytes)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Outgoing Traffic",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (datacenter) (hcloud_server_outgoing_traffic_bytes)",
     "legendFormat": "{{datacenter}}"
    },
    {
     "expr": "sum (hcloud_server_outgoing_traffic_bytes)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "$servers Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "repeat": "servers",
   "targets": [
    {}
   ]
  },
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(hcloud_server_running{name=~\"$servers\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(hcloud_server_memory_bytes{name=~\"$servers\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name, datacenter) (hcloud_server_incoming_traffic_bytes{name=~\"$servers\"})",
     "legendFormat": "{{name}}/{{datacenter}}"
    }
   ]
  },
  {
   "title": "Outgoing Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name, datacenter) (hcloud_server_outgoing_traffic_bytes{name=~\"$servers\"})",
     "legendFormat": "{{name}}/{{datacenter}}"
    }
   ]
  },
  {
   "title": "Disk Size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(hcloud_server_disk_bytes{name=~\"$servers\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backup Enabled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(hcloud_server_backup{name=~\"$servers\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(hcloud_server_cores{name=~\"$servers\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}