{
 "title": "Jitsi Meet",
 "description": "Dashboard for Jitsi Meet Exporter",
 "tags": [ "jitsi" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jitsi_jvb_stress,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Key metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bitrate download",
   "type": "stat",
   "description": "The total incoming bitrate for the video bridge in kilobits per second.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "jitsi_jvb_incoming_bitrate" }
   ]
  },
  {
   "title": "Bitrate upload",
   "type": "stat",
   "description": "The total outgoing bitrate for the video bridge in kilobits per second.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "jitsi_jvb_outgoing_bitrate" }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "description": "The number of Java threads that the video bridge is using.",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "jitsi_jvb_thread_count" }
   ]
  },
  {
   "title": "Video streams",
   "type": "stat",
   "description": "An estimation of the number of current video streams forwarded by the bridge.",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "jitsi_jvb_active_endpoints", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RTT",
   "type": "stat",
   "description": "An average value (in milliseconds) of the RTT across all streams.",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "jitsi_jvb_average_rtt" }
   ]
  },
  {
   "title": "Completed conferences",
   "type": "stat",
   "description": "The sum of the lengths of all completed conferences, in seconds.",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "jitsi_jvb_conferences_completed_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Biggest conference",
   "type": "stat",
   "description": "The number of participants in the largest conference currently hosted on the bridge.",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(jitsi_jvb_largest_conference)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total conferences",
   "type": "stat",
   "description": "The total number of conferences created on the bridge.",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "jitsi_jvb_conferences_created_total"
    }
   ]
  },
  {
   "title": "Conferences",
   "type": "timeseries",
   "description": "The current number of conferences.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "jitsi_jvb_conferences", "legendFormat": "conferences" },
    { "expr": "jitsi_jvb_conferences_p2p", "legendFormat": "p2p conferences" }
   ]
  },
  {
   "title": "Participants",
   "type": "timeseries",
   "description": "The current number of participants.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "jitsi_jvb_current_visitors", "legendFormat": "participants" }
   ]
  },
  { "title": "Additional metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Bitrate",
   "type": "timeseries",
   "description": "The total incoming/outgoing bitrate for the video bridge in kilobits per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    { "expr": "jitsi_jvb_incoming_bitrate", "legendFormat": "download" },
    { "expr": "jitsi_jvb_outgoing_bitrate", "legendFormat": "upload" }
   ]
  },
  {
   "title": "Package rate",
   "type": "timeseries",
   "description": " The total incoming/outgoing packet rate for the video bridge in packets per second.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(jitsi_jvb_packets_received_total[$__rate_interval])",
     "legendFormat": "download"
    },
    {
     "expr": "rate(jitsi_jvb_packets_sent_total[$__rate_interval])",
     "legendFormat": "upload"
    }
   ]
  },
  {
   "title": "Lost RTP packets",
   "type": "timeseries",
   "description": "The fraction of lost incoming RTP packets. This is based on RTP sequence numbers and is relatively accurate.\nThe fraction of lost outgoing RTP packets. This is based on incoming RTCP Receiver Reports, and an attempt to subtract the fraction of packets that were not sent (i.e. were lost before they reached the bridge). Further, this is averaged over all streams of all users as opposed to all packets, so it is not correctly weighted. This is not accurate, but may be a useful metric nonetheless.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jitsi_jvb_incoming_loss_fraction",
     "legendFormat": "download"
    },
    {
     "expr": "jitsi_jvb_outgoing_loss_fraction",
     "legendFormat": "upload"
    }
   ]
  },
  {
   "title": "Jitter aggregate",
   "type": "timeseries",
   "description": "Experimental. An average value (in milliseconds) of the jitter calculated for incoming and outgoing streams. This hasn't been tested and it is currently not known whether the values are correct or not.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "jitsi_jitter_aggregate{instance=~\"$instance.*\"} ",
     "legendFormat": "jitter"
    }
   ]
  },
  {
   "title": "RTT",
   "type": "timeseries",
   "description": "An average value (in milliseconds) of the RTT across all streams.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "jitsi_jvb_average_rtt", "legendFormat": "rtt" }
   ]
  },
  {
   "title": "Audio/Video channels",
   "type": "timeseries",
   "description": "The current number of audio/video channels.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jitsi_jvb_conferences_by_audio_sender_count",
     "legendFormat": "audio channels"
    },
    {
     "expr": "jitsi_jvb_conferences_by_size_count",
     "legendFormat": "video channels"
    }
   ]
  },
  {
   "title": "Sent/Received websockets",
   "type": "timeseries",
   "description": "The total number messages sent/received through COLIBRI web sockets.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(jitsi_jvb_colibri_web_socket_messages_received_total[$__rate_interval]) ",
     "legendFormat": "received"
    },
    {
     "expr": "rate(jitsi_jvb_colibri_web_socket_messages_sent_total[$__rate_interval]) ",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Failed conferences",
   "type": "timeseries",
   "description": "The rate of failed conferences on the bridge. A conference is marked as failed when all of its channels have failed. A channel is marked as failed if it had no payload activity.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(jitsi_jvb_endpoints_dtls_failed_total[$__rate_interval]) ",
     "legendFormat": "failed conferences"
    },
    {
     "expr": "rate(jitsi_jvb_ice_failed_total[$__rate_interval]) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sent/Received messages",
   "type": "timeseries",
   "description": "The total number messages sent/received through data channels.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(jitsi_jvb_data_channel_messages_received_total[$__rate_interval]) ",
     "legendFormat": "received"
    },
    {
     "expr": "rate(jitsi_jvb_data_channel_messages_sent_total[$__rate_interval]) ",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Videobridge stress level",
   "type": "timeseries",
   "description": "Stress level reported to Jicofo by the videobridge.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "jitsi_jvb_stress", "legendFormat": "stress level" }
   ]
  }
 ]
}