{
 "title": "RPI Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Nodes Down",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(up{job=\"rpi_exporter\", instance !~ \"nas.*\"}, \"instance_name\", \"$1\", \"instance\", \"(.*):(.*)\") == 0",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "Fan Speed (RPM)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rpi_fan_rpm", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Fan Speed (PWM Level)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rpi_fan_pwm_level", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max_over_time(rpi_cpu_temperature_celsius[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GPU Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max_over_time(rpi_gpu_temperature_celsius[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Fan RPM",
   "type": "timeseries",
   "description": "Only works for Pi 5",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    { "expr": "rpi_fan_rpm", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Fan PWM Level",
   "type": "timeseries",
   "description": "Indicates the PWM Level for Pi4 running PoE HAT",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 21 },
   "targets": [
    { "expr": "rpi_fan_pwm_level", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}