{
 "title": "Adguard Exporter",
 "description": "This is a Adguard dashboard when using the https://github.com/ebrianne/adguard-exporter Prometheus exporter",
 "tags": [ "adguard" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(adguard_num_dns_queries, hostname)"
    }
   },
   { "name": "datasource", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "AdGuard Home",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adguard_running{hostname=~'$node'}"
    }
   ]
  },
  {
   "title": "Protection",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adguard_protection_enabled{hostname=~'$node'}"
    }
   ]
  },
  {
   "title": "Processing TIme",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "adguard_avg_processing_time{hostname=~'$node'}",
     "legendFormat": "{{ legend }}"
    }
   ]
  },
  {
   "title": "Domains being blocked",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(adguard_num_dns_queries{hostname=~'$node'}[$__rate_interval])*60"
    }
   ]
  },
  {
   "title": "Domains being blocked",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adguard_num_blocked_filtering{hostname=\"$node\"\n          }"
    }
   ]
  },
  {
   "title": "Percent of ads blocked",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adguard_num_blocked_filtering{hostname=~'$node'} / adguard_num_dns_queries{hostname=~'$node'} * 100"
    }
   ]
  },
  {
   "title": "DNS Requests / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(adguard_num_dns_queries{hostname=~'$node'}[$__rate_interval])*60",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Ads blocked / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(adguard_num_blocked_filtering[$__rate_interval])*60",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "% of ads blocked",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "adguard_num_blocked_filtering{hostname=~'$node'} / adguard_num_dns_queries{hostname=~'$node'} * 100",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Total DNS queries all of types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "adguard_num_dns_queries{hostname=~'$node'} - adguard_num_blocked_filtering{hostname=~'$node'}\n",
     "legendFormat": "Legit traffic {{ hostname }}"
    },
    {
     "expr": "adguard_num_blocked_filtering{hostname=~'$node'}",
     "legendFormat": "Blocked traffic {{ hostname }}"
    },
    {
     "expr": "adguard_num_dns_queries{hostname=~'$node'}",
     "legendFormat": "Total traffic {{ hostname }}"
    }
   ]
  },
  {
   "title": "Ads blocked",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "adguard_num_blocked_filtering{hostname=~'$node'}",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "DNS Query Types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "adguard_query_types{hostname=~'$node'}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Replies by type",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adguard_query_types{hostname=~'$node'}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Replies by type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "adguard_query_types{hostname=~'$node'}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Top ads domains (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "topk(10, sum by(domain, hostname) (adguard_top_blocked_domains{hostname=\"$node\"\n          }))",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "Top clients",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "topk(10, sum by(client, hostname) (adguard_top_clients{hostname=\"$node\"\n          }))",
     "legendFormat": "{{ client }}"
    }
   ]
  }
 ]
}