{
 "title": "Urlshortener / Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Currently active shortlinks",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(urlshortener_active_redirects)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Calls to short URLs",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(urlshortener_shortlink_invocation)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distribution of shortlink calls",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "urlshortener_shortlink_invocation",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Distribution over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "urlshortener_shortlink_invocation",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Shortlink/sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "irate(urlshortener_shortlink_invocation[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Shortlinks over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "urlshortener_shortlink_invocation",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}