apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability

resources:
  - ../../../bases/grafana-oncall

generators:
  - ./secret-generator.yaml

patches:
  - target:
      kind: Ingress
      group: networking.k8s.io
      version: v1
    patch: |-
      - op: remove
        path: /metadata/annotations/cert-manager.io~1issuer

  - target:
      kind: StatefulSet
      group: apps
      version: v1
      name: "/*"
    patch: |-
      - op: replace
        path: /spec/template/spec/affinity/podAntiAffinity/preferredDuringSchedulingIgnoredDuringExecution/0/topologyKey
        value: topology.kubernetes.io/zone
