apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: loki-sm
  namespace: observability
spec:
  endpoints:
    - path: /metrics
      port: http-metrics
      relabelings:
        - replacement: observability/$1
          sourceLabels:
            - job
          targetLabel: job
        - replacement: loki
          targetLabel: cluster
      scheme: http
  selector:
    matchExpressions:
      - key: prometheus.io/service-monitor
        operator: NotIn
        values:
          - "false"
    matchLabels:
      app.kubernetes.io/instance: loki
      app.kubernetes.io/name: loki
