{
 "title": "Adguard Exporter",
 "description": "This is a Adguard dashboard when using the https://github.com/ebrianne/adguard-exporter Prometheus exporter",
 "tags": [ "adguard" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(adguard_num_dns_queries, hostname)"
    }
   },
   { "name": "datasource", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (hostname) (adguard_running{hostname=~'$node'})"
    }
   ]
  },
  {
   "title": "Processing TIme",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (hostname) (adguard_avg_processing_time{hostname=~'$node'})",
     "legendFormat": "{{ legend }}"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{instance=~\"$node:9100\",mode=\"idle\"}[1m])) by (instance))*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of requests blocked as ad",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (hostname) (adguard_num_blocked_filtering{hostname=~'$node'} / adguard_num_dns_queries{hostname=~'$node'} * 100)"
    }
   ]
  },
  {
   "title": "DNS Queries Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (hostname) (adguard_num_dns_queries{hostname=\"$node\"})"
    }
   ]
  },
  {
   "title": "Replies by type",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (adguard_query_types{hostname=~'$node'})",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Protection",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (hostname) (adguard_protection_enabled{hostname=~'$node'})"
    }
   ]
  },
  {
   "title": "DNS Queries",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (hostname) (rate(adguard_num_dns_queries{hostname=~'$node'}[$__rate_interval])*60)"
    }
   ]
  },
  {
   "title": "Used RAM Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node:9100\"} / (node_memory_MemTotal_bytes{instance=~\"$node:9100\"})))* 100"
    }
   ]
  },
  {
   "title": "Domains being blocked",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (hostname) (rate(adguard_num_blocked_filtering[$__rate_interval])*60) <= 1000000"
    }
   ]
  },
  {
   "title": "Domains being blocked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (hostname) (adguard_num_blocked_filtering{hostname=\"$node\"})"
    }
   ]
  },
  {
   "title": "AdGuard Home",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "DNS Requests / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (hostname) (rate(adguard_num_dns_queries{hostname=~'$node'}[$__rate_interval])*60)<= 1000000",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Ads blocked / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (hostname) (rate(adguard_num_blocked_filtering[$__rate_interval])*60) <= 1000000",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "% of requests blocked as ad",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (hostname) (adguard_num_blocked_filtering{hostname=~'$node'} / adguard_num_dns_queries{hostname=~'$node'} * 100)",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Total DNS queries all of types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (hostname) (adguard_num_dns_queries{hostname=~'$node'} - adguard_num_blocked_filtering{hostname=~'$node'})",
     "legendFormat": "Legit traffic {{ hostname }}"
    },
    {
     "expr": "sum by (hostname) (adguard_num_blocked_filtering{hostname=~'$node'})",
     "legendFormat": "Blocked traffic {{ hostname }}"
    },
    {
     "expr": "sum by (hostname) (adguard_num_dns_queries{hostname=~'$node'})",
     "legendFormat": "Total traffic {{ hostname }}"
    }
   ]
  },
  {
   "title": "Requests blocked as ad",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (hostname) (adguard_num_blocked_filtering{hostname=~'$node'})",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "DNS Query Types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (type) (adguard_query_types{hostname=~'$node'})",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Replies by type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (adguard_query_types{hostname=~'$node'})",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Top ads domains (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "topk(10, sum by(domain) (adguard_top_blocked_domains{hostname=\"$node\"}))",
     "legendFormat": "{{ domain }}"
    }
   ]
  },
  {
   "title": "Top clients",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "topk(10, sum by(client) (adguard_top_clients{hostname=\"$node\"}))",
     "legendFormat": "{{ client }}"
    }
   ]
  },
  { "title": "Node Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "CPU% Basic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{instance=~\"$node:9100\",mode=\"idle\"}[1m])) by (instance))*100",
     "legendFormat": "Total"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node:9100\",mode=\"system\"}[1m])) by (instance) *100",
     "legendFormat": "System"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node:9100\",mode=\"user\"}[1m])) by (instance) *100",
     "legendFormat": "User"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node:9100\",mode=\"iowait\"}[1m])) by (instance) *100",
     "legendFormat": "IOWait"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node:9100\"} - node_memory_MemAvailable_bytes{instance=~\"$node:9100\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$node:9100\"}",
     "legendFormat": "Avaliable"
    }
   ]
  }
 ]
}