{
 "title": "Urlshortener / Overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Currently active shortlinks",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(urlshortener_active_redirects)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distribution of shortlink calls",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(urlshortener_shortlink_invocation) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Latency /:shortlink",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "traces_spanmetrics_latency_bucket{service=\"urlshortener\", span_name=\"/:shortlink\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Latency /home",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "traces_spanmetrics_latency_bucket{service=\"urlshortener-ui\", span_name=\"/home\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Calls to short URLs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(urlshortener_shortlink_invocation)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shortlink/sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "irate(urlshortener_shortlink_invocation[1m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Distribution over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "urlshortener_shortlink_invocation",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Shortlinks over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "urlshortener_shortlink_invocation",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}