apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability

resources:
  - ../../../bases/grafana-tempo
  - ./tailscale-ingress.yaml

generators:
  - ./secret-generator.yaml

patchesJson6902:
  - target:
      kind: HorizontalPodAutoscaler
      group: autoscaling
      version: v2beta1
      name: ".*"
    patch: |-
      - op: replace
        path: "/apiVersion"
        value: "autoscaling/v2"

      - op: remove
        path: "/spec/metrics/0/resource/targetAverageUtilization"

      - op: add
        path: /spec/metrics/0/resource/target
        value:
          type: Utilization
          averageUtilization: 60

  - target:
      kind: Deployment
      group: apps
      version: v1
      name: "tempo-distributor"
    patch: |-
      - op: add
        path: /spec/strategy
        value:
          rollingUpdate:
            maxSurge: 0
            maxUnavailable: 1

  - target:
      kind: StatefulSet
      group: apps
      version: v1
      name: "tempo-memcached"
    patch: |-
      - op: replace
        path: /spec/template/spec/affinity/podAntiAffinity/requiredDuringSchedulingIgnoredDuringExecution/0/topologyKey
        value: topology.kubernetes.io/region

  - target:
      kind: StatefulSet
      group: apps
      version: v1
      name: "tempo-ingester"
    patch: |-
      - op: replace
        path: /spec/template/spec/affinity/podAntiAffinity/preferredDuringSchedulingIgnoredDuringExecution/0/podAffinityTerm/topologyKey
        value: topology.kubernetes.io/region

  - target:
      kind: StatefulSet
      group: apps
      version: v1
      name: "tempo-ingester"
    patch: |-
      - op: replace
        path: /spec/template/spec/affinity/podAntiAffinity/preferredDuringSchedulingIgnoredDuringExecution/1/podAffinityTerm/topologyKey
        value: topology.kubernetes.io/zone

  - target:
      kind: PodDisruptionBudget
      group: policy
      version: v1beta1
      name: tempo-ingester
    patch: |-
      - op: replace
        path: /apiVersion
        value: policy/v1

  - target:
      kind: PodDisruptionBudget
      group: policy
      version: v1beta1
      name: tempo-distributor
    patch: |-
      - op: replace
        path: /apiVersion
        value: policy/v1
