apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 70.2.1
    releaseName: prometheus-stack
    namespace: monitoring
    valuesFile: helm-values.yaml
