apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chaos-mesh
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: chaos-mesh
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/chaos-mesh
    repoURL: https://github.com/SpechtLabs/k8s-deployment.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - kind: CustomResourceDefinition
      group: apiextensions.k8s.io/v1
      name: schedules.chaos-mesh.org
      jsonPointers:
        - /
    - kind: CustomResourceDefinition
      group: apiextensions.k8s.io/v1
      name: workflownodes.chaos-mesh.org
      jsonPointers:
        - /
