apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hugo-hosting
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: hugo-hoster
            path: charts/hugo-hoster
          - name: hugo-pages
            path: manifests/hugo-pages
  template:
    metadata:
      name: "{{name}}"
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      destination:
        namespace: "hugo-hoster"
        server: https://kubernetes.default.svc
      project: default
      source:
        path: "{{path}}"
        repoURL: https://github.com/cedi-dev/k8smanifests.git
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
